// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MusicPortal.Data;

namespace MusicPortal.Migrations
{
    [DbContext(typeof(MusicPortalContext))]
    [Migration("20210711175407_musicPortal")]
    partial class musicPortal
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MusicPortal.Models.Authenticatio", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("UName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UPassword")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Authenticatio");
                });

            modelBuilder.Entity("MusicPortal.Models.Music", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("MLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Mdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Mtitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("singerid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("singerid");

                    b.ToTable("Music");
                });

            modelBuilder.Entity("MusicPortal.Models.Singer", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contact")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Singer");
                });

            modelBuilder.Entity("MusicPortal.Models.Video", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("MName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Mdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Mtitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("singerid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("singerid");

                    b.ToTable("Video");
                });

            modelBuilder.Entity("MusicPortal.Models.Music", b =>
                {
                    b.HasOne("MusicPortal.Models.Singer", "singer")
                        .WithMany()
                        .HasForeignKey("singerid");
                });

            modelBuilder.Entity("MusicPortal.Models.Video", b =>
                {
                    b.HasOne("MusicPortal.Models.Singer", "singer")
                        .WithMany()
                        .HasForeignKey("singerid");
                });
#pragma warning restore 612, 618
        }
    }
}
